### PR TITLE
`eframe`: Add `winuser` feature to `winapi` to fix unresolved import

### PR DESCRIPTION
**Pull request by varphone**
After merging PR #4036, build errors occurred in eframe-related applications:

```log
error[E0432]: unresolved import `winapi::um::winuser`
   --> crates\eframe\src\native\app_icon.rs:83:9
    |
83  |     use winapi::um::winuser;
    |         ^^^^^^^^^^^^^^^^^^^ no `winuser` in `um`
    |
note: found an item that was configured out
   --> C:\Users\Varphone\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winapi-0.3.9\src\um\mod.rs:290:37
    |
290 | #[cfg(feature = "winuser")] pub mod winuser;
    |                                     ^^^^^^^
    = note: the item is gated behind the `winuser` feature

For more information about this error, try `rustc --explain E0432`.
error: could not compile `eframe` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
```

### CODE REVIEW

**Review by emilk — APPROVED** [review]
Thanks!

Next time the CI will catch this: https://github.com/emilk/egui/pull/4038

**Comment by quietvoid** [comment]
Any chance for a bugfix release?

**Comment by emilk** [comment]
A workaround is to just add this is to your own `Cargo.toml`:

```
[target.'cfg(any(target_os = "windows"))'.dependencies]
winapi = { version = "0.3.9", features = ["winuser"] }
```

**Comment by oscargus** [comment]
Just for reference, this happens independently of #4036. I'm still on egui 0.25 and was bitten by this. My best guess is that `arboard` had this feature pinned in 3.2.1, but when updated to 3.3.1 (which should have been a non-breaking change), the dependency on `winapi` was removed and therefore the feature was removed.
