### ISSUE TITLE
egui demo website egui.rs does not load

### ISSUE THREAD

**Issue by olofos** [emilk/egui#2943]
**Describe the bug**

The egui.rs website does not load but gives a gray page with the error message

"An error occurred during loading:
TypeError: handle.then is not a function
Make sure you use a modern browser with WebGL and WASM enabled."

This happens both with an up to date Chrome on my laptop and with Chrome on my Android phone

**To Reproduce**
1. Go to [https://www.egui.rs/](https://www.egui.rs/)
2. Instead of a nice demo I'm met with the error message above

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.1 Ulyssa  
 - Browser: chrome 
 - Version: 112.0.5615.165
 
**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S22
 - OS: Android 13
 - Browser: chrome
 - Version: 112.0.5615.101

**Comment by randall-fulton** [comment]
I see the same on Firefox and something similar (though the message is slightly different) on mobile Safari.

**Comment by vars1ty** [comment]
Experiencing the same on Firefox and Ungoogled Chromium.
@emilk ?
https://github.com/emilk/egui/blob/ac50fa0d9425f15c286e7e1ba3258241f655e638/docs/index.html#L138
Issue introduced in commit ac50fa0d9425f15c286e7e1ba3258241f655e638 it seems like.

**Comment by MattiaLaviola** [comment]
I'm experiencing the same issue on Windows 10 with Chrome Version 112.0.5615.137 (Official Build) (64-bit)

**Comment by JoshLambda** [comment]
Just a few pointers for people being stuck while waiting for a fix:

* If meanwhile you want to run de the demo locally you can have a look at: https://github.com/not-fl3/egui-miniquad

* Examples source code from demo can be found here: https://github.com/emilk/egui/tree/latest/crates/egui_demo_lib

**Comment by ardocrat** [comment]
Just try this command to use egui locally:
`cargo run --release -p egui_demo_app`

**Comment by olofos** [comment]
This seems to be fixed by c82604fe51e8dff1c4bdced578e8e1522db51bf1

**Comment by fralonra** [comment]
Error happened to me again.

![image](https://github.com/emilk/egui/assets/20400873/bdb78e3c-5d20-43de-a19c-15432194f619)

OS: archlinux
Chrome: 114.0.5735.133

**Comment by oletf** [comment]
same here 
![image](https://github.com/emilk/egui/assets/109208726/f26787b9-b5ad-4583-a6ab-55df99b80899)

OS: `Windows 10 22H2 19045.4046`
Firefox: `122.0.1`

**Comment by emilk** [comment]
Make sure your browsers have WebGL support: https://get.webgl.org/

**Comment by oletf** [comment]
alright my bad, thanks for the test website.
turns out my nvidia driver was out of date and updating it solved it !
