### ISSUE TITLE
label click handling & Scrolling Example Broken in Egui 11

### ISSUE THREAD

**Issue by jmw992** [emilk/egui#334]
**Describe the bug**
As the title mentions the ui.label.clicked() seems not to be working with egui & eframe 0.11, and can be seen in the demo lib scrolling example. 

**Screenshots**
![brokenLabelClick](https://user-images.githubusercontent.com/15371018/115996861-fc41df00-a5ae-11eb-835c-0f9885daed9e.gif)

**Expected behavior**
Those labels should be turning yellow.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
Not a big deal selectable_label is working fine and this may be intended.

 I was hoping to put in a fix myself but I'm having issues building the windows egui_demo_lib from the main branch, but I'm running into errors when I go to build with both nightly & stable releases.  I didn't see any pre install requirements mentioned in the egui_demo_lib are there steps required beyond cargo build?

Build error I get
```
D:\Personal\BayswaterPC\Code\egui\egui_demo_lib>cargo build
   Compiling autocfg v1.0.1
   Compiling getrandom v0.2.2
   Compiling version_check v0.9.3
   Compiling ttf-parser v0.6.2
   Compiling cfg-if v1.0.0
   Compiling once_cell v1.7.2
   Compiling ab_glyph_rasterizer v0.1.4
   Compiling emath v0.11.0 (D:\Personal\BayswaterPC\Code\egui\emath)
   Compiling ahash v0.7.2
   Compiling num-traits v0.2.14
   Compiling owned_ttf_parser v0.6.0
   Compiling rusttype v0.9.2
   Compiling ordered-float v2.1.1
   Compiling epaint v0.11.0 (D:\Personal\BayswaterPC\Code\egui\epaint)
error[E0432]: unresolved import `atomic_refcell`
  --> epaint\src\mutex.rs:78:9
   |
78 | pub use atomic_refcell::AtomicRefMut as MutexGuard;
   |         ^^^^^^^^^^^^^^ use of undeclared crate or module `atomic_refcell`

error[E0432]: unresolved import `atomic_refcell`
   --> epaint\src\mutex.rs:103:9
    |
103 | pub use atomic_refcell::AtomicRef as RwLockReadGuard;
    |         ^^^^^^^^^^^^^^ use of undeclared crate or module `atomic_refcell`

error[E0432]: unresolved import `atomic_refcell`
   --> epaint\src\mutex.rs:107:9
    |
107 | pub use atomic_refcell::AtomicRefMut as RwLockWriteGuard;
    |         ^^^^^^^^^^^^^^ use of undeclared crate or module `atomic_refcell`

error[E0433]: failed to resolve: use of undeclared crate or module `atomic_refcell`
  --> epaint\src\mutex.rs:83:21
   |
83 | pub struct Mutex<T>(atomic_refcell::AtomicRefCell<T>);
   |                     ^^^^^^^^^^^^^^ use of undeclared crate or module `atomic_refcell`

error[E0433]: failed to resolve: use of undeclared crate or module `atomic_refcell`
  --> epaint\src\mutex.rs:89:14
   |
89 |         Self(atomic_refcell::AtomicRefCell::new(val))
   |              ^^^^^^^^^^^^^^ use of undeclared crate or module `atomic_refcell`

error[E0433]: failed to resolve: use of undeclared crate or module `atomic_refcell`
   --> epaint\src\mutex.rs:112:22
    |
112 | pub struct RwLock<T>(atomic_refcell::AtomicRefCell<T>);
    |                      ^^^^^^^^^^^^^^ use of undeclared crate or module `atomic_refcell`

error[E0433]: failed to resolve: use of undeclared crate or module `atomic_refcell`
   --> epaint\src\mutex.rs:118:14
    |
118 |         Self(atomic_refcell::AtomicRefCell::new(val))
    |              ^^^^^^^^^^^^^^ use of undeclared crate or module `atomic_refcell`

error[E0282]: type annotations needed
  --> epaint\src\mutex.rs:82:10
   |
82 | #[derive(Default)]
   |          ^^^^^^^ cannot infer type for type parameter `T` declared on the struct `Mutex`
   |
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0282]: type annotations needed
   --> epaint\src\mutex.rs:111:10
    |
111 | #[derive(Default)]
    |          ^^^^^^^ cannot infer type for type parameter `T` declared on the struct `RwLock`
    |
    = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 9 previous errors

Some errors have detailed explanations: E0282, E0432, E0433.
For more information about an error, try `rustc --explain E0282`.
error: could not compile `epaint`

To learn more, run the command again with --verbose.
```

**Comment by emilk** [comment]
They are not meant to be clickable.

As for you build errors: the solution is simply `cd ..`. Don't know why cargo isn't more helpful there
