### ISSUE TITLE
0.35 AlphaFromCoverage import fails

### ISSUE THREAD

**Issue by White-Rabbit-Scientific** [emilk/egui#8269]
use egui::epaint::image::AlphaFromCoverage;

unresolved import egui::epaint::image::AlphaFromCoverage
no AlphaFromCoverage in image (rustc E0432)

Works in 0.34 release, fails in 0.35 release.
