### ISSUE TITLE
dark_light doesn't compile on macOS 10.13 - can detection be disabled?

### ISSUE THREAD

**Issue by sourcebox** [emilk/egui#1305]
With 0.17 I get a linker error on macOS 10.13:

```
Undefined symbols for architecture x86_64:
            "_NSAppearanceNameDarkAqua", referenced from:
                dark_light::macos::is_dark_mode_enabled::hb7132683b5ba2217 in libdark_light-a47262a41b3d5450.rlib(dark_light-a47262a41b3d5450.dark_light.54f6d069-cgu.2.rcgu.o)
            "_NSAppearanceNameAccessibilityHighContrastAqua", referenced from:
                dark_light::macos::is_dark_mode_enabled::hb7132683b5ba2217 in libdark_light-a47262a41b3d5450.rlib(dark_light-a47262a41b3d5450.dark_light.54f6d069-cgu.2.rcgu.o)
            "_NSAppearanceNameAccessibilityHighContrastDarkAqua", referenced from:
                dark_light::macos::is_dark_mode_enabled::hb7132683b5ba2217 in libdark_light-a47262a41b3d5450.rlib(dark_light-a47262a41b3d5450.dark_light.54f6d069-cgu.2.rcgu.o)
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I don't need the automatic detection anyway, so is it possible to deactivate it via a feature flag?

**Comment by frewsxcv** [comment]
This could be fixed upstream in dark-light, though it's worth mentioning macOS 10.13 is very much not supported anymore by Apple

**Comment by sourcebox** [comment]
I'll open a issue on the `dark-light` repo for this. Nevertheless, I request to put a feature gate on this, similar as it's done with `serde` via the `persistence` feature.
Before 0.17, it was possible to build and run `egui` based apps even on macOS 10.11 without any problems. With `dark-light`, the minimum requirement is raised to macOS 10.14, in which dark mode was introduced. 

Supporting older operating systems is essential to me, regardless what Apple thinks on this. It's way more than having an eye candy feature like automatic theme-switching. Some users can not update their systems, even if they want to.

**Comment by emilk** [comment]
@sourcebox please link to the `dark-light` issue here so we can track it.

`dark-light` is already an optional feature of `egui-winit`, so making it an optional feature of `egui_glow` and `eframe` too should be pretty easy. Wanna make a PR for it?

**Comment by sourcebox** [comment]
Sorry, should have done this already. Here's the issue: frewsxcv/rust-dark-light#14

**Comment by collin-kemper** [comment]
This is also now addressed in PR #1437

**Comment by sourcebox** [comment]
@collin-kemper Thank you very much for this PR!

**Comment by emilk** [comment]
`dark-light` is now opt-in, until it works well on all platforms: https://github.com/emilk/egui/pull/1437
