### ISSUE TITLE
[WIP] Issues encountered when upgrading `eframe` from 0.8.0 to 0.11.0

### ISSUE THREAD

**Issue by follower** [emilk/egui#294]
**TL;DR: Upgrade `rustc` before upgrading `eframe`/`egui`.**

----

[WIP: Because I'm a perfectionist. :D ]

### `cargo` `update` versioning issue.

 * [TODO]

###  `rustc` (minimum) version issues

 * [TODO]

 * Initial version:

    ```
    $ rustup check
    stable-x86_64-unknown-linux-gnu - Update available : 1.49.0 (e1884a8e3 2020-12-29) -> 1.51.0 (2fd73fabe 2021-03-23)
    ```

### Per version migration issues

0.9.0

 * `Triangles` -> `Mesh`.

0.10.0

* [TODO] :

```
   Compiling egui v0.10.0
error[E0658]: use of unstable library feature 'bool_to_option'
   --> /home/philip/.cargo/registry/src/github.com-1ecc6299db9ec823/egui-0.10.0/src/widgets/drag_value.rs:262:26
    |
262 |                         .then(|| drag_state.last_dragged_value)
    |                          ^^^^
    |
    = note: see issue #64260 <https://github.com/rust-lang/rust/issues/64260> for more information

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `egui`
```

0.11.0

 * [TODO] (Due to https://github.com/emilk/egui/commit/1f965d16a2b2268b4311e844351a44e1d9e2f9ae.) :

```
  Downloaded epi v0.11.0
error: failed to parse manifest at `/home/philip/.cargo/registry/src/github.com-1ecc6299db9ec823/epi-0.11.0/Cargo.toml`

Caused by:
  feature `resolver` is required

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can add
  `cargo-features = ["resolver"]` to enable this feature
```

**Comment by emilk** [comment]
You need to use latest stable rust when using egui. This is documented at https://docs.rs/egui/0.11.0/egui/
